services:
  redis:
    image: redis:7-alpine
    restart: on-failure

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./media:/app/media
    restart: on-failure
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_data || true;
             gunicorn configs.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  celery:
    build: .
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    command: celery -A configs worker -l info
    restart: on-failure

  celery-beat:
    build: .
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    command: celery -A configs beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: on-failure
