# Generated by Django 5.1.4 on 2026-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccy', models.CharField(max_length=3)),
                ('base_ccy', models.CharField(default='UAH', max_length=3)),
                ('buy', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sale', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'currency_rates',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
